import 'package:get/get.dart';

class Loacalstring extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
   'en_Us' : {
    "Welcome" : "Welcome To The GEM" ,
    "Explore" : "Explore" ,
    "seeall" : "See All",
    "Akhenaten" : "King Akhenaten",
    "Hatshbsot" : "King Hatshbsot",
    "Sonsrt1" : "King Sonsrt 1",
    "Sonsrt2" : "King Sonsrt 2",
    "Tahtmos" : "King Tahtmos",
    "image" : "Photo",
    "video" : "Video",
    "Ticket_dis" : "For Getting Discount For The Res-ervation, book From Your Booth",
    "adult" : "Adult",
    "student" : "Student",
    "youth" : "Youth",
    "senior" : "Senior",
    "L_e" : "L.E",
    "pay" : "pay now",
    "payy" : "For getting ticket click pay now",
    "login" : "Log IN",
    "signup" : "Sign Up",
    "Ex" : "Explore The Musuem",
    "GUID" : "Explore with Tour Guide",
    "Royal" : "ROYAL JOURNEY",
    "top" : "Top Favorites",
    "category" : "Categories",
    "Show" : "Show",
    "Our" : "ABOUT US Our mobile application offers A virtual tour Of one Of the most historical ages pharaonic civilizations.But That's not all- we go beyond by bring-ing history to life through Ai-powered lip synchronization, historical characters within the musuem tell their stories.offering tourists a unique and inspiring experience. our 360- degree virtual tour creates a sense of immersion, allowing users to delve into Egypt'rich history and civilization.",
    "whats" : "WhatsAPP",
    "Face" : "FaceBook",
    "insta" : "Instagram",
    "not" : "Notification",
    "fav" : "Favorites",
    "rate" : "Rating Us",
    "language" : "Languages",
    "Logout" : "Log Out",
    "have" : "You Have 2 Notification Today ! ",
    "not1" : "Pharaera Community Say Goodmorning",
    "not2" : "Hello! Come And Visit Our New VRroom",
    "ago":"Ago",
    "submit":"Submit",
    "How" : "How would you rate our app?",
    "feed":"Your feedback has been submitted.",
    "enter":"Enter Your Feedback",
    "email":"Email",
    "password":"Password",
    "firstname":"First name",
    "Conform":"Conform Password",
    "search": "Search",
    "profile" : "Profile" , 
    "contact" : "Contact Us",
    "home" : "Home",
    "ABOUT" : "About US",
    "thanks":"Thanks",
    "ok" : "Ok",
    "Forget":"Forget Password",
    "haveaccount":"Have An Account ?",
    "pharera" : "pharera",
    "Exhibition" : "Exhibition Pictures",
    "ExhibitionV" : "Exhibition Video",
    "DownloadF" : "Download failed. Please try again.",
    "DownloadE" : "Download Error.",
    "DownloadT" : "Download task ID:",
    "Permission" : "Permission denied. Please enable storage permission.",
    "Directory" : "Directory not found.",
    "ticket":"Ticket",
    "Exhibition1" : "Exhibition",
    "pharaohs" : "Pharaohs",
    "wellcome" : "Welcome",
    "incomplete" :"Incomplete",
    "please" : "Please rate and provide feedback.",
    "provide" : "Provide feedback...",
    "how" : "How would you rate our app?",
    "enterp" : "Enter Password",
    "create" : "CREATE ACCOUNT" ,
    "name" : "FULL NAME" ,
    "web" : "WebView",
    "lets" : "Lets get started..",
    "setting" : "Settings",
    "weelcome" : "Welcome Page",
    "signin" : "SIGN IN",
    "exihibtion" : "Exhibitions",
    "Tickets" : "Tickets",
    "Permision":"Permission denied. Please enable storage permission.",
    "file" : "File downloaded to:",
    "arabic" : "ARABIC" , 
    "English" : "ENGLISH"
   },
   'ar_arb' : {
    "Welcome": "مرحبًا بكم",
    "Explore": "استكشاف",
    "seeall": "عرض الكل",
    "Akhenaten": "الملك أخناتون",
    "Hatshbsot": "الملك حتشبسوت",
    "Sonsrt1": "الملك سنوسرت الأول",
    "Sonsrt2": "الملك سنوسرت الثاني",
    "Tahtmos": "الملك تحتمس",
    "image": "صورة",
    "video": "فيديو",
    "Ticket_dis": "للحصول على خصم للحجز، احجز من كشكك",
    "adult": "بالغ",
    "student": "طالب",
    "youth": "شباب",
    "senior": "كبير السن",
    "L_e": "ج.م",
    "pay": "ادفع الآن",
    "payy": "للحصول على التذكرة انقر على ادفع الآن",
    "login": "تسجيل الدخول",
    "signup": "إنشاء حساب",
    "Ex": "استكشاف المتحف",
    "GUID": "استكشاف مع مرشد سياحي",
    "Royal": "رحلة ملكية",
    "top": "الأكثر تفضيلاً",
    "category": "الفئات",
    "Show": "عرض",
    "Our": "حولنا تطبيقنا المحمول يوفر جولة افتراضية لأحد أقدم العصور الحضارات الفرعونية. ولكن هذا ليس كل شيء - نحن نذهب أبعد من ذلك بإحياء التاريخ من خلال التزامن الشفوي المدعوم بالذكاء الاصطناعي، حيث تحكي الشخصيات التاريخية داخل المتحف قصصها. نقدم للسياح تجربة فريدة وملهمة. جولتنا الافتراضية بزاوية 360 درجة تخلق شعورًا بالانغماس، مما يتيح للمستخدمين التعمق في تاريخ وحضارة مصر الغنية.",
    "whats": "واتساب",
    "Face": "فيسبوك",
    "insta": "إنستغرام",
    "not": "الإشعارات",
    "fav": "المفضلات",
    "rate": "قيمنا",
    "language": "اللغات",
    "Logout": "تسجيل الخروج",
    "have": "لديك إشعارين اليوم!",
    "not1": "مجتمع الفرعنة يقول صباح الخير",
    "not2": "مرحبًا! تعال وزر غرفة الواقع الافتراضي الجديدة لدينا",
    "submit": "إرسال",
    "How": "كيف تقيم تطبيقنا؟",
    "feed": "تم إرسال ملاحظاتك.",
    "enter": "أدخل ملاحظاتك",
    "email": "البريد الإلكتروني",
    "password": "كلمة المرور",
    "firstname": "الاسم الأول",
    "Conform": "تأكيد كلمة المرور",
    "search": "بحث",
    "profile": "الملف الشخصي",
    "contact": "اتصل بنا",
    "home": "الرئيسية",
    "ABOUT": "عنا",
    "thanks": "شكرًا",
    "ok": "موافق",
    "Forget": "نسيت كلمة المرور",
    "haveaccount": "هل لديك حساب؟",
    "Exhibition": "صور المعرض",
    "ExhibitionV": "فيديو المعرض",
    "DownloadF": "فشل التنزيل. حاول مرة أخرى.",
    "DownloadE": "خطأ في التنزيل.",
    "DownloadT": "معرف مهمة التنزيل:",
    "Permission": "تم رفض الإذن. يرجى تمكين إذن التخزين.",
    "Directory": "الدليل غير موجود.",
    "ticket": "تذكرة",
    "Exhibition1": "معرض",
    "pharaohs": "الفراعنة",
    "wellcome": "مرحبًا",
    "incomplete": "غير مكتمل",
    "please": "يرجى التقييم وتقديم الملاحظات.",
    "provide": "تقديم الملاحظات...",
    "how": "كيف تقيم تطبيقنا؟",
    "enterp": "أدخل كلمة المرور",
    "create": "إنشاء حساب",
    "name": "الاسم الكامل",
    "web": "عرض ويب",
    "lets": "لنبدأ..",
    "setting": "الإعدادات",
    "weelcome": "صفحة الترحيب",
    "signin": "تسجيل الدخول",
    "exihibtion": "المعارض",
    "Tickets": "التذاكر",
    "Permision": "تم رفض الإذن. يرجى تمكين إذن التخزين.",
    "file": "تم تنزيل الملف إلى:",
    "arabic": "العربية",
    "English": "الإنجليزية"
   }
  }
  
  
  
  ;


}