import 'package:get/get.dart'; 

class LOcalString extends Translations{
@override
  
  Map<String ,  Map<String , String> > get keys => {
    'en_Us': {
      "Welcome" : "Welcome To The Gym" ,
    "Explore" : "Explore" ,
    "seeall" : "See All",
    "Akhenaten" : "King Akhenaten",
    "Hatshbsot" : "King Hatshbsot",
    "Sonsrt1" : "King Sonsrt 1",
    "Sonsrt2" : "King Sonsrt 2",
    "Tahtmos" : "King Tahtmos",
    "image" : "Photo",
    "video" : "Video",
    "Ticket_dis" : "For Getting Discount For The Res-ervation, book From Your Booth",
    "adult" : "Adult",
    "student" : "Student",
    "youth" : "Youth",
    "senior" : "Senior",
    "L_e" : "L.E",
    "pay" : "Pay Now",
    "login" : "Log IN",
    "signup" : "Sign Up",
    "Ex" : "Explore The Musuem",
    "GUID" : "Explore with Tour Guide",
    "Royal" : "ROYAL JOURNEY",
    "top" : "Top Favorites",
    "category" : "Categories",
    "Show" : "Show",
    "Our" : "ABOUT US Our mobile application offers A virtual tour Of one Of the most historical ages pharaonic civilizations.But That's not all- we go beyond by bring-ing history to life through Ai-powered lip synchronization, historical characters within the musuem tell their stories.offering tourists a unique and inspiring experience. our 360- degree virtual tour creates a sense of immersion, allowing users to delve into Egypt'rich history and civilization.",
    "whats" : "WhatsAPP",
    "Face" : "FaceBook",
    "insta" : "Instagram",
    "not" : "Notification",
    "fav" : "Favorites",
    "rate" : "Rating Us",
    "language" : "Languages",
    "Logout" : "Log Out",
    "have" : "You Have 2 Notification Today ! ",
    "not1" : "Pharaera Community Say Goodmorning",
    "not2" : "Hello! Come And Visit Our New VRroom",
    "ago":"Ago",
    "submit":"Submit",
    "feed":"Your Feedback Is Welcome",
    "enter":"Enter Your Feedback",
    "email":"Email",
    "password":"Password",
    "firstname":"First name",
    "Conform":"Conform Password",
    "search": "Search",
    "profile" : "Profile" , 
    "contact" : "Contact Us",
    "home" : "Home",
    "ABOUT" : "ABOUT US",
    "thanks":"Thank You For Your Feedback!",
    "ok" : "Ok",
    "Forget":"Forget Password",
    "haveaccount":"Have An Account ?",
    "pharera" : "pharera"

    },
    'ar_arb':{
      "Welcome" : "مرحبًا بك في جيم ",
    "Explore" : "استكشف",
    "seeall" : "عرض الكل",
    "Akhenaten" : "الملك أخناتون",
    "Hatshbsot" : "الملكة حتشبسوت",
    "Sonsrt1" : "الملك سنسرت الأول",
    "Sonsrt2" : "الملك سنسرت الثاني",
    "Tahtmos" : "الملك تحتمس",
    "image" : "الصور",
    "video" : "الفيديو",
    "Ticket_dis" : "للحصول على خصم على الحجز، احجز من جناحك",
    "adult" : "بالغ",
    "student" : "طالب",
    "youth" : "شباب",
    "senior" : "حديثي التخرج",
    "L_e" : "ج.م",
    "pay" : "ادفع الآن",
    "login" : "تسجيل الدخول",
    "signup" : "انشاء حساب",
    "Ex" : "استكشاف المتحف",
    "GUID" : "استكشاف مع مرشد سياحي",
    "Royal" : "رحلة ملكية",
    "top" : "الأكثر إعجابًا",
    "category" : "الفئات",
    "Show" : "عرض",
    "Our" : "من نحن تطبيقنا الجوال يقدم جولة افتراضية في أحد أعمدة الحضارات التاريخية الفرعونية. ولكن هذا ليس كل شيء - نحن نتجاوز من خلال جلب التاريخ للحياة من خلال تزامن الشفاه بقوة الذكاء الصناعي، حيث يروي الشخصيات التاريخية داخل المتحف قصصهم، مما يقدم تجربة فريدة وملهمة للسياح. جولتنا الافتراضية بزاوية 360 درجة تخلق شعورًا بالانغماس، مما يتيح للمستخدمين الغوص في تاريخ مصر الغني وحضارتها.",
    "whats" : "واتساب",
    "Face" : "فيسبوك",
    "insta" : "إنستجرام",
    "not" : "الإشعارات",
    "fav" : "المفضلة",
    "rate" : "تقييمنا",
    "language" : "اللغات",
    "Logout" : "تسجيل الخروج",
    "have" : "لديك 2 إشعار اليوم!",
    "not1" : "مجتمع فارايرا يقول صباح الخير",
    "not2" : "مرحبًا! تعال وزر غرفتنا الافتراضية الجديدة",
    "ago": "منذ",
    "submit":"إرسال",
    "feed":"مرحبًا بتعليقاتك",
    "enter":"أدخل تعليقك",
    "email": "البريد الإلكتروني",
    "password": "كلمة المرور",
    "firstname": "الاسم الأول",
    "Conform": "تأكيد كلمة المرور",
    "search": "بحث",
    "profile": "الملف الشخصي",
    "contact": "اتصل بنا",
    "home": "الرئيسية",
    "ABOUT": "نبذة عنا",
    "thanks": "شكرًا لتقديم ملاحظاتك!",
    "ok": "حسنًا",
    "Forget": "نسيت كلمة المرور",
    "haveaccount": "هل لديك حساب؟",
    "pharera" : "pharera"
    }
  };
 

}