name: iOS-ipa-test01

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS v0.9
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      # Install CocoaPods dependencies
      - name: Install CocoaPods
        run: pod install --repo-update
        working-directory: ios

      # Verify GoogleService-Info.plist is present
      - name: Check GoogleService-Info.plist
        run: ls -l ios/Runner/GoogleService-Info.plist

      # Debugging step to print the Podfile
      - name: Print Podfile
        run: cat ios/Podfile

      # Debugging step to print the Podfile.lock
      - name: Print Podfile.lock
        run: cat ios/Podfile.lock

      - run: flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
