name: iOS-ipa-test01

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS v0.9
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod setup
        working-directory: ios

      - name: Install Flutter dependencies
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Get packages
        run: flutter pub get

      - name: Create or update Podfile
        run: |
          cat <<EOF > Podfile
          platform :ios, '12.0'
          use_frameworks!
          target 'Runner' do
            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
            pod 'Firebase/Core', '10.25.0'
            pod 'Firebase/Auth', '10.25.0'
            pod 'Firebase/Firestore', '10.25.0'
            pod 'Firebase/Storage', '10.25.0'
          end
          EOF
        working-directory: ios

      - name: Update CocoaPods dependencies
        run: pod install --repo-update
        working-directory: ios

      - name: Clear CocoaPods cache and clean install
        run: |
          rm -rf ~/Library/Caches/CocoaPods
          pod cache clean --all
          pod deintegrate
          pod install
        working-directory: ios

      - run: pod repo update
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
