name: iOS-ipa-test01

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS v0.9
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      - name: Create or update Podfile for iOS 12.0
        run: |
          if [ ! -f ios/Podfile ]; then
            echo "Creating Podfile"
            echo "platform :ios, '12.0'" > ios/Podfile
            echo "" >> ios/Podfile
            cat ios/Podfile >> ios/Podfile
          fi
          if ! grep -q "platform :ios, '12.0'" ios/Podfile; then
            echo "Updating Podfile"
            sed -i '' '1i\
            platform :ios, '\''12.0'\''
            ' ios/Podfile
          fi
          cat ios/Podfile

      - name: Install CocoaPods
        run: pod install --repo-update
        working-directory: ios

      - name: Verify GoogleService-Info.plist
        run: ls -l ios/Runner/GoogleService-Info.plist

      - run: flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
